variable "vsphere_server" {}
variable "vsphere_user" {}
variable "vsphere_password" {}
variable "vsphere_datacenter" {}
variable "vsphere_resource_pool" {}
variable "vsphere_datastore" {}
variable "vsphere_network" {}
variable "Template_Name" {}
variable "Master0_VM_NAME" {}
variable "Master0_Host_Name" {}
variable "Domain_Name" {}
variable "Master0_VM_IP" {}
variable "NETMASK" {}
variable "DNS_SERVER" {}
variable "Gateway" {}
variable "CPUS" {}
variable "Memory" {}
variable "VMDISK_SIZE" {}
variable "vm_password" {}
variable "Master1_VM_IP" {}
variable "Master2_VM_IP" {}
variable "Master1_Host_Name" {}
variable "Master2_Host_Name" {}
variable "Master1_VM_NAME" {}
variable "Master2_VM_NAME" {}
variable "Worker0_VM_IP" {}
variable "Worker1_VM_IP" {}
variable "Worker0_Host_Name" {}
variable "Worker1_Host_Name" {}
variable "Worker0_VM_NAME" {}
variable "Worker1_VM_NAME" {}
